### ISSUE TITLE
你好，我集成了身份证识别，当扫描没反应啊，是不是还有别的步骤？谢谢

### ISSUE THREAD

**Issue by ximida-haha** [shouzhong/Scanner#1]

**Comment by shouzhong** [comment]
有没有调用scannerView.setEnableIdCard(true);

**Comment by ximida-haha** [comment]
有调用的，
com.tomcat.ocr.idcard I/exocrenginec.so: Java_exocr_exocrengine_EXOCREngine_nativeInit
com.tomcat.ocr.idcard I/exocrenginec.so: Init Failed!
和这个错误有关吗？

**Comment by shouzhong** [comment]
@ximida-haha 有没有完整的日志

**Comment by ximida-haha** [comment]
com.tomcat.ocr.idcard I/exocrenginec.so: Java_exocr_exocrengine_EXOCREngine_nativeInit
com.tomcat.ocr.idcard I/exocrenginec.so: Init Failed!
com.tomcat.ocr.idcard E/kalu: checkDict ==> code = -80008
com.tomcat.ocr.idcard I/exocrenginec.so: Java_exocr_exocrengine_EXOCREngine_nativeDone
com.tomcat.ocr.idcard E/kalu: clearDict ==> code = 0

基本上是重复这些log的一直

**Comment by shouzhong** [comment]
看下在你那app文件夹下的files文件夹里有没有idcard/zocr0.lib

**Comment by ximida-haha** [comment]
看了，有哦

**Comment by ximida-haha** [comment]
orc文件夹里面也有对应的身份证照片，当就是没走回掉，我试用二维码就是可以正常回调的

**Comment by shouzhong** [comment]
用我的那个app-demo可以吗

**Comment by ximida-haha** [comment]
我没运行你的demo，我直接自己搞了一个demo来引用你的库来使用的，奇怪了

**Comment by shouzhong** [comment]
你是直接调ScannerUtils.decodeIdCard吗

**Comment by ximida-haha** [comment]
不是，就走你目前最新的代码示例

**Comment by ximida-haha** [comment]
要不我们加个联系方式吧，不然这样聊有点费劲

**Comment by shouzhong** [comment]
你qq多少，我qq好像别人加不了

**Comment by ximida-haha** [comment]
491079893

**Comment by Derek-Zh** [comment]
遇到同样的问题，求问怎么解决的

**Comment by ximida-haha** [comment]
看看log输出什么？

**Comment by Derek-Zh** [comment]
> 看看log输出什么？

跟你log一模一样，但是换个手机又没问题，头疼

**Comment by shouzhong** [comment]
@Derek-Zh 我那个demo可以吗

**Comment by Derek-Zh** [comment]
> @Derek-Zh 我那个demo可以吗

demo可以，集成到我的APP中又不行，就是不停报这个-80008错误

**Comment by shouzhong** [comment]
@Derek-Zh 在你那app文件夹下的files文件夹里有没有idcard/zocr0.lib

**Comment by Derek-Zh** [comment]
> @Derek-Zh 在你那app文件夹下的files文件夹里有没有idcard/zocr0.lib

有的

**Comment by shouzhong** [comment]
> 
> 
> > @Derek-Zh 在你那app文件夹下的files文件夹里有没有idcard/zocr0.lib
> 
> 有的

试下新版本

**Comment by Derek-Zh** [comment]
> 试下新版本

试了，不行，不知道为啥会报字典初始化错误

**Comment by shouzhong** [comment]
> 
> 
> > 试下新版本
> 
> 试了，不行，不知道为啥会报字典初始化错误

再试下新版本

**Comment by Derek-Zh** [comment]
> 再试下新版本

有空再尝试。已经用另一种方式解决了，直接干掉了的arm64-v8a的库，只用arm-v7a的库
