### ISSUE TITLE
驾驶证识别不准

### ISSUE THREAD

**Issue by yang94** [shouzhong/Scanner#14]
您好，您这里面驾驶证识别效果很不理想，能不能更新驾驶证识别包

**Comment by shouzhong** [comment]
如果你自己有的话可以用自己的，没有的话我也无能为力，目前只有这个。当然如果你使用次数不多的话可以考虑大厂的，多的话只能找人定制或者大厂充钱（不合算，按次数收费）

**Comment by yang94** [comment]
那这里能通过访问相册来识别吗

**Comment by shouzhong** [comment]
可以，ScannerUtils.decodeDrivingLicense，获取图片你要自己写，或者直接用这个https://github.com/LuckSiege/PictureSelector

**Comment by yang94** [comment]
OK，谢谢，我刚学安卓三周，有很多都不会，谢谢

**Comment by yang94** [comment]
这个驾驶证识别好像准一点，中文这块不会错误太多，https://github.com/fanqieVip/AndroidOcrLibs
