### ISSUE TITLE
重复进入识别身份证无法有效识别

### ISSUE THREAD

**Issue by imagine-star** [shouzhong/Scanner#25]
识别身份证的时候关闭activity再开启就没法识别到图片了，跟断点进去发现是检测字典那边过不去，一直返回false，不知道该怎么解决这个问题，有没有朋友遇到过

**Comment by liuxuesong001** [comment]
我也遇到了，请问怎么解决的？
<img width="398" alt="image" src="https://user-images.githubusercontent.com/9588185/169205830-7b092283-1483-4c53-ab59-4bb41457d96e.png">

**Comment by shouzhong** [comment]
只能说这个身份证识别库不够成熟，我也没有源码，如果这个需求是很重要的，建议还是接大厂的
