### ISSUE TITLE
使用这个识别框架腾讯管家会报毒

### ISSUE THREAD

**Issue by ydmmocoo** [shouzhong/Scanner#37]
目前公司的应用内使用 了此框架，最近突然收到了OPPO用户说是使用本公司的应用报毒，经过几天的排查，最后去掉此框架后，不报毒了。应用宝也被下架了，最近在申诉中。。。

**Comment by ydmmocoo** [comment]
使用virustotal检测只有腾讯的会报毒，目前也不确定是不是此框架的问题，反正去掉就是不报毒了，很无语

**Comment by shouzhong** [comment]
这就不清楚了，也没权限啥的，代码里也没做什么东西

**Comment by ydmmocoo** [comment]
后面申诉成功了，不是这个库的问题
