### ISSUE TITLE
黄图识别不可用

### ISSUE THREAD

**Issue by geeklx** [shouzhong/Scanner#49]
请指教~

**Comment by shouzhong** [comment]
这个我没仔细测过，但是我之前测得结果应该是没问题的
我使用的是这个库https://github.com/devzwy/open_nsfw_android，或许你可以更新下模型
![2022 05 07_吴一丰 6c023a57471a6cd56c5204045083a9d9](https://user-images.githubusercontent.com/27850869/167243272-8d86808e-bf27-4365-80d3-7f1a4c1b5515.png)

**Comment by geeklx** [comment]
> 这个我没仔细测过，但是我之前测得结果应该是没问题的 我使用的是这个库[https://github.com/devzwy/open_nsfw_android，或许你可以更新下模型](https://github.com/devzwy/open_nsfw_android%EF%BC%8C%E6%88%96%E8%AE%B8%E4%BD%A0%E5%8F%AF%E4%BB%A5%E6%9B%B4%E6%96%B0%E4%B8%8B%E6%A8%A1%E5%9E%8B) ![2022 05 07_吴一丰 6c023a57471a6cd56c5204045083a9d9](https://user-images.githubusercontent.com/27850869/167243272-8d86808e-bf27-4365-80d3-7f1a4c1b5515.png)

这个可以！
