### ISSUE TITLE
预览页面 修改了一下就识别不了了？

### ISSUE THREAD

**Issue by wflian** [shouzhong/Scanner#8]
ViewFinder demo里面 宽度高度 默认比例 0.8  可以识别。我改成宽度0.8占比 宽高比1：1.6 绘制的区域是正常的，但是不能识别了。什么原因？

**Comment by shouzhong** [comment]
先试下1.1.1版本，然后测试机的屏幕分辨率以及哪个识别不了方便说下吗

**Comment by wflian** [comment]
手机 畅享9 Plus 分辨率 1080x2340

**Comment by shouzhong** [comment]
> 
> 
> 手机 畅享9 Plus
> 分辨率 1080x2340
> 预览区域 竖屏全屏包含状态栏
> 使用库 身份证识别（第二种方式）
> 设置了setRotateDegree90Recognition（true）
> 宽度0.8 高度0.8 识别可以
> 宽度0.8 高度 = 1.6x宽度 识别不可以

加下群777891894，这里说不方便

**Comment by LeeUsun** [comment]
> ViewFinder demo里面 宽度高度 默认比例 0.8 可以识别。我改成宽度0.8占比 宽高比1：1.6 绘制的区域是正常的，但是不能识别了。什么原因？

你好，我也是遇到这种情况，机型是华为nova3，改成身份证的比例就不好扫描了，请问你最后怎么处理的

**Comment by wflian** [comment]
用第一种方式
