### ISSUE TITLE
导入项目报错

### ISSUE THREAD

**Issue by Elfran1025** [shouzhong/Scanner#9]
提示：Could not read script 'D:\StudioProjects\Scanner\bankcard\bintray.gradle' as it does not exist. 请问应该怎么解决呢？

**Comment by shouzhong** [comment]
把build.gradle里面的apply from: 'bintray.gradle'那行删了

**Comment by Elfran1025** [comment]
已经把 第12行换成了对应的路径了，现在又出现了 
org.gradle.internal.exceptions.LocationAwareException: executing external native build for cmake D:\StudioProjects\Scanner\licenseplate\CMakeLists.txt
